# Generated by Django 4.2.11 on 2024-10-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.CharField(default='', max_length=20),
        ),
    ]
